const jobs = [
    {
        id: 0,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 1,
        title:"Welder",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 2,
        title:"Finish Welders/Auto Mechanics",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 3,
        title:"Service Center Technician",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 4,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 5,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 6,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 7,
        title:"2nd Shift Service Center Technician",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 8,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 9,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 10,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 11,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },{
        id: 12,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 13,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 14,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 15,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 16,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 17,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 18,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 19,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 20,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 21,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 22,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },
    {
        id: 23,
        title:"Welders-All Shifts",
        para:'<u style="color: #eb5444;font-style: italic;"><strong style="color: #eb5444;">KEY DUTIES &amp; RESPONSIBILITIES:</strong></u>'+ '<p style="font-style: italic;color:#1f2631;font-weight:0;font-family: Poppins,sans-serif;">Duties and responsibilities of skilled and unskilled welders differ as per their expertise levels. In general, the duties and responsibilities of a welder are:  </p>' + '<p>&nbsp; </p>' + '<u> </u>'+'<ol style="color: #404350;"><li>Weld metals according to customer or employer requirements.  </li><li>Ensure high safety measures while working such as donning protective gear for the face and body.  </li><li>Operate heavy equipment such as industrial saws. </li><li>Examine the equipment after welding and advise maintenance of defects. </li><li>Plan/set up of welding operations before beginning.  </li><li>Read blueprints and weld according to the plan.  </li><li>Senior welders will supervise welding operations of junior welders.  </li><li>Train junior and entry level welders.  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>EXPERTISE REQUIRED:</u></b><u> </u> &nbsp; </p>' +  '<p>&nbsp; </p>' + '<ol style="color: #404350;"><li>A thorough knowledge of the different methods and symbols of welding and ability to successfully pass the company certification for all welding applications it certifies on.  </li><li>A thorough knowledge about safety precautions while working.  </li><li>Ability to read blueprints and understand instructions.  </li><li>Ability to analyze work at hand and execute welding procedure per training certifications.  </li><li>Good decision-making skills.  </li><li>Ability to work in heat and smoke.  </li><li>Must pass medical questionnaire.  </li><li>Must be able to finish work within given time  </li></ol>' +  '<p>&nbsp; </p>' +'<p><b><u>MINIMUM QUALIFICATIONS:</u></b><b><u> </u></b> </p>' + '<p>&nbsp; </p>' + '<ul style="color: #404350;"><li><p>A high school diploma or GED preferred, but not required.  </p></li><li><p>Vocational course in welding or previous welding training.  </p></li><li><p>Compensation is commensurate on level of proficiency when taking welding test for certification.  </p></li></ul>' + '<p>&nbsp; </p>' + '<p><b><u>PHYSICAL REQUIREMENTS: </u></b> </p>' +  '<p>&nbsp; </p>' + '<p style="color: #404350;">This job operates in a manufacturing plant environment. While performing the duties of this job, the team member is regularly required to talk or hear. The team member frequently is required to stand (sometimes for extended periods); walk; use hands to finger, handle or feel; and reach with hands and arms, and lift up to 35 pounds. The team member may, at times, sit, bend, stoop, squat, reach overhead, or crawl (may be in confined spaces). The team member is expected to perform repetitive tasks using their hands, and have the ability to climb ladders and/or work in high places. </p>'
    },

]


const pagination = {
    currentPage : 1,
    maxPage: 0,
    itemPerPage: 0,
    items: [],
    allItems:[],

    init(data, itemPerPage){
        this.currentPage = 1;
        this.itemPerPage = itemPerPage
        this.maxPage = Math.ceil(data.length / itemPerPage )
        this.allItems = data;
        this.setItems();
    },

    setItems(){
        this.items = this.allItems.slice((this.currentPage - 1 ) * this.itemPerPage, this.itemPerPage * this.currentPage);
    },

    hasNext(){
        return this.maxPage > this.currentPage;
    },
    hasPrev(){
        return this.currentPage > 1
    },
    nextPage(){
        this.currentPage = this.hasNext() ? this.currentPage + 1 : this.currentPage
        this.setItems();
    },
    prevPage(){
        this.currentPage = this.hasPrev() ? this.currentPage - 1 : this.currentPage
        this.setItems();
    },
    setItemPerPage(item_per_page){
        this.itemPerPage = item_per_page;
        this.currentPage = 1;
        this.setMaxPage();
        this.setItems();
    },
    setMaxPage(){
        this.maxPage = Math.ceil(this.allItems.length / this.itemPerPage )
    }
}



function render(){
    pagination.init(jobs, 10)
    renderJobs(pagination.items);
    renderButtons("next-btn", "prev-btn");
    renderCurrentPage("current-page");
    renderMaxItems("max-items");
    renderSelect("select-per-page")
    addEventListenersToElements()
}




const renderSelect = (selectId) => {
    let select = document.getElementById(selectId);
    let lastOption = document.createElement("option");
    lastOption.value = pagination.allItems.length;
    lastOption.innerText = pagination.allItems.length;

    select.appendChild(lastOption);
}

const renderButtons = (nextBtnId, preBtnId) => {
    const activeBtnClass = "active";
    let nextBtn = document.getElementById(nextBtnId);
    let prevBtn = document.getElementById(preBtnId);

    if ( pagination.hasNext() ){
        nextBtn.classList.add(activeBtnClass)
        prevBtn.disabled = false;
    }else{
        nextBtn.classList.remove(activeBtnClass)
        prevBtn.disabled = true;
    }

    if ( pagination.hasPrev() ){
        prevBtn.classList.add(activeBtnClass)
        prevBtn.disabled = false;
    }else{
        prevBtn.classList.remove(activeBtnClass)
        prevBtn.disabled = true;
    }

}

const addEventListenersToElements = () => {
   document.getElementById("next-btn").addEventListener("click", _ => {
       nextPage();
   });
   document.getElementById("prev-btn").addEventListener("click",_ => {
       prevPage();
   });

   let select = document.getElementById("select-per-page");
   select.addEventListener("change", function (){
       const item_per_page = select.value;
       changePageNumber(item_per_page);
   })

    document.getElementById("all-btn").addEventListener("click", function (){
        select.value = pagination.allItems.length;
        changePageNumber(select.value);
    })

}

const changePageNumber = (item_per_page) => {
    pagination.setItemPerPage(item_per_page);
    renderJobs(pagination.items);
    renderButtons("next-btn", "prev-btn");
    renderCurrentPage("current-page");
    renderMaxItems("max-items")
}

const nextPage  = () => {
    pagination.nextPage();
    renderJobs(pagination.items);
    renderButtons("next-btn", "prev-btn");
    renderCurrentPage("current-page");
    renderMaxItems("max-items")

}

const prevPage = () => {
    pagination.prevPage();
    renderJobs(pagination.items);
    renderButtons("next-btn", "prev-btn");
    renderCurrentPage("current-page");
    renderMaxItems("max-items")
}

const renderCurrentPage = (currenPageId) => {
    let currentPageSpan = document.getElementById(currenPageId);
    currentPageSpan.innerText = pagination.currentPage;
}


const renderMaxItems = (maxItemsId) => {
    let maxItemsSpan = document.getElementById(maxItemsId);
    maxItemsSpan.innerText = pagination.allItems.length.toString();
}



const renderJobs = (jobs) => {
    let card = document.querySelector("#cards");
    card.innerHTML = "";

    jobs.forEach(job => {
        const img = document.createElement("img");
        img.alt = "card-photo";
        img.src = "./images/qaq.jpg";
        img.classList = ['card-image'];

        const image_holder_div = document.createElement("div");
        image_holder_div.appendChild(img);

        const strongTitle = document.createElement('strong');
        strongTitle.innerText = job.title;

        const card_comments_div = document.createElement("div");
        card_comments_div.classList = ["card-comments"];
        card_comments_div.appendChild(strongTitle);
        card_comments_div.innerHTML += "-per year"

        const paragraph = document.createElement("p");
        paragraph.classList = ["panel"];
        paragraph.innerHTML = job.para

        const cart_button = document.createElement("a");
        cart_button.innerText = "Detail";
        cart_button.classList = ["card-btn"]
        cart_button.role = "button";


        const card_content_div = document.createElement("div");
        card_content_div.classList = ['cards-content'];
        card_content_div.onclick = ()=> {
            if (paragraph.style.display === "flex") {
                paragraph.style.display = "none";
            } else {
                paragraph.style.display = "flex";
            }
        }

        card_content_div.appendChild(image_holder_div);
        card_content_div.appendChild(card_comments_div);
        card_content_div.appendChild(cart_button)

        card.appendChild(card_content_div);
        card.appendChild(paragraph);
    })
}
